sonar.projectKey=risktrace-control-tower-frontend
sonar.projectName=RiskTrace Control Tower Frontend
sonar.projectBaseDir=.
sonar.sources=apps/frontend/src
sonar.tests=apps/frontend/tests
sonar.sourceEncoding=UTF-8
sonar.typescript.tsconfigPath=apps/frontend/tsconfig.json
sonar.javascript.lcov.reportPaths=apps/frontend/coverage/lcov.info
sonar.exclusions=apps/frontend/node_modules/**,apps/frontend/dist/**
