server:
  http_listen_port: 3200
  log_level: warn

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318

ingester:
  max_block_duration: 5m
  trace_idle_period: 10s
  max_block_bytes: 1_073_741_824

compactor:
  compaction:
    block_retention: 336h

metrics_generator:
  registry:
    external_labels:
      source: tempo
      cluster: rwa-control-tower
  storage:
    path: /tmp/tempo/generator/wal
    remote_write:
      - url: http://prometheus.monitoring.svc.cluster.local:9090/api/v1/write
        send_exemplars: true
  processor:
    service_graphs:
      enable_virtual_node_label: true
    span_metrics:
      dimensions:
        - http.method
        - http.status_code
        - http.target
        - rpc.service

storage:
  trace:
    backend: s3
    s3:
      bucket: "{{ TEMPO_S3_BUCKET }}"
      region: "{{ AWS_REGION }}"
      forcepathstyle: false
    wal:
      path: /tmp/tempo/wal
    local:
      path: /tmp/tempo/blocks

querier:
  max_concurrent_queries: 20
  search:
    max_duration: 0

query_frontend:
  search:
    duration_slo: 5s
    throughput_bytes_slo: 1.073741824e+09
  trace_by_id:
    duration_slo: 5s

overrides:
  defaults:
    metrics_generator:
      processors: [service-graphs, span-metrics]
    ingestion:
      rate_limit_bytes: 20_000_000
      burst_size_bytes: 25_000_000
    read:
      max_bytes_per_trace: 5_000_000
